[profile.default]
src = "src"
out = "contractArtifacts"
libs = ["lib"]
solc = "0.8.24"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
